language: php

php:
    - 5.6
    - 7.0

install:
    - composer self-update
    - composer install
    - npm install

before_script:
    - #Code that creates and seeds my database and so on

script: ./node_modules/codeceptjs-webdriverio/codecept.js run --steps