<h1>Edit a meetup</h1>

<?php
    $form = $this->form; /* @var $form \Zend\Form\Form */
?>

<?= $this->form()->openTag($form); ?>

<div>
<?= $this->formRow($form->get('title')->setValue($meetup->getTitle())) ?>
</div>

<div>
<?= $this->formRow($form->get('description')->setValue($meetup->getDescription())) ?>
</div>

<div>
<?= $this->formRow($form->get('stime')->setValue($meetup->getStime())) ?>
</div>

<div>
<?= $this->formRow($form->get('etime')->setValue($meetup->getEtime())) ?>
</div>

<div>
    <?= $this->formRow($form->get('creator')->setValue($meetup->getCreator())) ?>
</div>

<div>
    <?= $this->formRow($form->get('company')->setValue($meetup->getCompany())) ?>
</div>

<div>
    <?= $this->formRow($form->get('participants')->setValue($meetup->getParticipants())) ?>
</div>

<div>
<?= $this->formInput($form->get('submit')) ?>
</div>

<?= $this->form()->closeTag($form); ?>
