<h1>Meetups</h1>

<table>
    <tr>
        <td>Id</td><td>Title</td><td>Description</td><td>Start time</td><td>End time</td><td>Options</td>
    </tr>
    <?php foreach ($this->meetups as $meetup): /* @var $meetup \Meetup\Entity\Meetup */ ?>
        <tr>
            <td><?= $meetup->getId() ?></td><td><?= $meetup->getTitle() ?></td><td><?= $meetup->getDescription() ?></td><td><?= $meetup->getStime() ?></td><td><?= $meetup->getEtime() ?></td><td><a href="<?= $this->url('meetup/edit', ['id' => $meetup->getId()]) ?>" class="btn btn-primary">Edit</a><a href="<?= $this->url('meetup/delete', ['id' => $meetup->getId()]) ?>" class="btn btn-primary">Delete</a><a href="<?= $this->url('meetup/show', ['id' => $meetup->getId()]) ?>" class="btn btn-primary">Show</a></td>
        </tr>
    <?php endforeach; ?>
</table>

<a href="<?= $this->url('meetup/add'); ?>" class="btn btn-primary">Add new</a>
