<h1>Edit an user</h1>

<?php
    $form = $this->form; /* @var $form \Zend\Form\Form */
?>

<?= $this->form()->openTag($form); ?>

<div>
<?= $this->formRow($form->get('firstname')->setValue($user->getFirstname())) ?>
</div>

<div>
<?= $this->formRow($form->get('lastname')->setValue($user->getLastname())) ?>
</div>

<div>
<?= $this->formRow($form->get('company')->setValue($user->getCompany())) ?>
</div>

<div>
<?= $this->formInput($form->get('submit')) ?>
</div>

<?= $this->form()->closeTag($form); ?>
